version: "3"

services:

  mail:
    image: instrumentisto/dovecot
    ports:
      - "143:143"
    expose:
      - "143"
    volumes:
      - "./mail/dovecot:/etc/dovecot"
      - "./mail/home:/home"

  node:
    build: ./node
    user: node
    ports:
      - "3003:3003"
      - "9229:9229"
    expose:
      - "3003"
      - "9229"
    working_dir: "/home/node/app"
    volumes:
      - "./node:/home/node/app"
    command: >
      sh -c "
      ./wait.sh db 3306 &&
      ./wait.sh mail 143 &&
      npm run-script make &&
      npm run-script migrate &&
      npm run-script watch"

  node-test:
    build: ./node
    user: node
    #environment:
    #  - NODE_ENV=test
    ports:
      - "3003:3003"
      - "9229:9229"
    expose:
      - "3003"
      - "9229"
    working_dir: "/home/node/app"
    volumes:
      - "./node:/home/node/app"
    command: >
      sh -c "
      ./wait.sh db 3306 &&
      ./wait.sh mail 143 &&
      npm run-script make &&
      npm run-script migrate &&
      while true; do npm run-script test; sleep 12; done"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=groupmail
      - MYSQL_USER=node
      - MYSQL_PASSWORD=node
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./db/sqldump:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    restart: always

# vim: noai:ts=2:sw=2
