version: "3"

services:

  mail:
    image: instrumentisto/dovecot
    ports:
      - "143:143"
    expose:
      - "143"
    volumes:
      - "./mail/dovecot:/etc/dovecot"
      - "./mail/home:/home"

  node:
    build: ./node
    user: node
    ports:
      - "3003:3003"
      - "9229:9229"
    expose:
      - "3003"
      - "9229"
    working_dir: "/home/node/app"
    volumes:
      - "./node:/home/node/app"
    command: >
      sh -c "
      while ! nc -z db 3306;
      do
        echo 'waiting for db 3306';
        sleep 2;
      done &&
      while ! nc -z mail 143;
      do
        echo 'waiting for mail 143';
        sleep 2;
      done &&
      npm run-script make &&
      npm run-script migrate &&
      npm run-script watch"

      #depends_on:
      #- db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=groupmail
      - MYSQL_USER=node
      - MYSQL_PASSWORD=node
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./db/sqldump:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    restart: always

# vim: noai:ts=2:sw=2
